---
  - name: Create {{ db_name }} database
    mysql_db:
      name: "{{ db_name }}" 
      state: present

  - name: Create {{ db_user }} database user and grant privileges
    mysql_user:
      name: "{{ db_user }}"
      password: "{{ db_pass }}"
      priv: "{{ db_name }}.*:ALL"
      host: "{{ WebServerIP }}"
      state: present
      update_password: on_create