---
# handlers file for roles/database
  - name: Reload firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
      enabled: yes
    listen: "firewall restart"

  - name: Reload Mariadb
    ansible.builtin.service:
      name: mariadb
      state: restarted
      enabled: yes
    listen: "mariadb restart"